name: Build ESP32 C3 Firmware

on:
  push:
    branches: [master]
    paths:
      - "firmware/**"
  pull_request:
    branches: [master]
    paths:
      - "firmware/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Build firmware
        working-directory: ./firmware
        run: |
          pio run

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: firmware-build
          path: firmware/.pio/build/
          retention-days: 7
