name: Run Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-firmware:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Run firmware tests
        working-directory: ./firmware
        run: |
          pio test

  test-react-native:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: AfterburnerControl/package-lock.json

      - name: Install dependencies
        working-directory: ./AfterburnerControl
        run: npm ci

      - name: Run React Native tests
        working-directory: ./AfterburnerControl
        run: |
          npm test -- --coverage --watchAll=false

      - name: Upload test coverage
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage
          path: AfterburnerControl/coverage/
          retention-days: 7
